### ISSUE TITLE
Way to expose resources attributes in a data to allow grafana and prometheus providers to work nicely

### ISSUE THREAD

**Issue by maxkoko-co** [terraform-aws-modules/terraform-aws-managed-service-grafana#10]
- Yes ✅: managed grafana and managed prometheus 

## Is your request related to a problem? Please describe.

When trying to provision grafana using grafana provider I cannot do it in the same terraform run, the common provider issue of resource not being known at the creation time for provider to refresh state, or being deleted on a destroy which results in some resources being orphaned in the terraform state making it invalid. 

## Describe the solution you'd like.

Right now both prometheus workspace data type, and grafana workspace data type are being found by id. ID is not in the outputs. It would also be preferable to be able to find those by { Tag = Name } rather then just by the id which allows other terraform runs to get those without creating a file just to pass id in between or read it directly from terraform stat (sic!) 

Except for being able to find a resource using data query by name it would also be preferable if grafana api keys would be in the attributes as well. Meaning other terraform run can get those staticly in the provider definition. 

Something like this:
```hcl
data "aws_grafana_workspace" "example" {
  filter {
    name   = "name"
    values = ["$MYENV-GRAFANA"]
}

provider "grafana" {
  url  = "https://${data.aws_grafana_workspace.example.endpoint}"
  auth = data.aws_grafana_workspace.example.auth_keys.admin.json
}
```

**Comment by bryantbiggs** [comment]
you will want to open this question on the provider https://github.com/hashicorp/terraform-provider-aws

We can only support what the provider supports
