### ISSUE TITLE
Module should not default to an enterprise licence 

### ISSUE THREAD

**Issue by pmason56** [terraform-aws-modules/terraform-aws-managed-service-grafana#18]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - Current version

## Is your request related to a problem? Please describe.

The ```aws_grafana_license_association``` defaults to ENTERPRISE. The enterprise licence has a large cost involved, I'm not sure if this will make the marketplace purchase but could inadvertently cause a cost spike. 

If possible it would be great to have the option to disable the ```aws_grafana_license_association``` resource on its own.

## Describe the solution you'd like.
Switch default from ENTERPRISE to ENTERPRISE_FREE_TRIAL and provide a variable to disable ```aws_grafana_license_association```

## Describe alternatives you've considered.
Will have to avoid using this module to not use the ```aws_grafana_license_association``` resource

**Comment by bryantbiggs** [comment]
you can set `associate_license` to `false`
