### ISSUE TITLE
Add new variable create_saml to be able to skip saml config

### ISSUE THREAD

**Issue by csantanapr** [terraform-aws-modules/terraform-aws-managed-service-grafana#19]
## Is your request related to a problem? Please describe.

I need a way to create the workspace, with SAML specify in `authentication_providers` but skipping aws_grafana_workspace_saml_configuration

The order of my scenario is like this
1. create `aws_grafana_workspace_saml_configuration` with `authentication_providers = ["SAML"]`
2. get the output `workspace_endpoint`
3. Deploy Keycloak with input `workspace_endpoint` (helm)
4. Get from Keycloak output the url for `idp_metadata_url`
5. Create `aws_grafana_workspace_saml_configuration` using output `workspace_id`

## Describe the solution you'd like.
New variable `create_saml` so I can set to `false`

## Describe alternatives you've considered.
Don't have any other

## Additional context
The scenario is for [EKS Blueprints GitOps](https://github.com/csantanapr/terraform-aws-eks-blueprints/blob/argo-multi-cluster/examples/gitops/argocd-multi-cluster/hub-cluster/main.tf#L335-L456)

**Comment by bryantbiggs** [comment]
closed in #20
