### ISSUE TITLE
Var for grafana_version 

### ISSUE THREAD

**Issue by Fran-Rg** [terraform-aws-modules/terraform-aws-managed-service-grafana#24]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform]
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
The grafana_workspace resource has support grafana_version but it's not possible to set it up: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace.html#grafana_version

## Describe the solution you'd like.
Add var.grafana_version

## Additional context
This is required to upgrade workspace version: Specifies the version of Grafana to support in the new workspace. Supported values are 8.4 and 9.4. If not specified, defaults to 8.4. Upgrading the workspace version isn't supported, however it's possible to copy content from the old version to the new one using AWS official [migration tool](https://github.com/aws-observability/amazon-managed-grafana-migrator).

**Comment by bryantbiggs** [comment]
this was added 2 months ago in #21

**Comment by Fran-Rg** [comment]
@bryantbiggs my bad... I loaded
https://registry.terraform.io/modules/terraform-aws-modules/managed-service-grafana/aws/1.4.0
instead of
https://registry.terraform.io/modules/terraform-aws-modules/managed-service-grafana/aws/latest
to check

Sorry about that
