### ISSUE TITLE
Add rotate for API keys

### ISSUE THREAD

**Issue by Sadarex** [terraform-aws-modules/terraform-aws-managed-service-grafana#26]
## Issue
The API keys created with the input `workspace_api_keys ` are not rotated when they expire.

## Describe the solution you'd like.
The keys should be replaced automatically at the next apply.

## Possible solution
I found a way to achieve this here:
https://github.com/hashicorp/terraform-provider-aws/issues/27043#issuecomment-1614947274

```
locals {
  expiration_days    = 30
  expiration_seconds = 60 * 60 * 24 * local.expiration_days
}

resource "time_rotating" "rotate" {
  rotation_days = local.expiration_days
}

resource "time_static" "rotate" {
  rfc3339 = time_rotating.rotate.rfc3339
}

resource "aws_grafana_workspace_api_key" "admin_key" {
  key_name        = # ...
  key_role        = # ...
  seconds_to_live = local.expiration_seconds
  workspace_id    = # ...

  lifecycle {
    replace_triggered_by = [
      time_static.rotate
    ]
  }
}
```

**Comment by andonovrnd** [comment]
I suppose if we get support for service accounts the use of api keys would be obfuscated , correct me if i am wrong tho. 
After all the api keys would be deprecated or are considered for deprecation. But yeah the issue you pointed out still stays you cannot manage dashboards , folders alarms etc with expired api key.

**Comment by andonovrnd** [comment]
In the meantime i found a nice workaround for this https://github.com/t04glovern/amazon-managed-grafana-api-key-rotation-terraform this solution is using the secrets manager to rotate keys and so far from my tests it seems to be working very smoothly

**Comment by JamesBelchamber** [comment]
If I created a PR to push the api keys into secrets manager, with a rotation lambda that rotated them once every x days, would that be acceptable to the project? I dunno if it's too much sprawl but I think this is a useful feature for anyone using AWS Managed Grafana.

**Comment by kriegster108** [comment]
bumping this, would like a solution

**Comment by Sadarex** [comment]
*pump*

Any comment from the maintainers? To include the workaround I found should be very easy and doesn't require any extra AWS resources.

**Comment by Sadarex** [comment]
pump
