### ISSUE TITLE
Broken SSO setup

### ISSUE THREAD

**Issue by hmih** [terraform-aws-modules/terraform-aws-managed-service-grafana#30]
## Description

I am constantly hitting a: `Error: creating Grafana Workspace: ValidationException: SSO is not enabled in any region.` when creating a new AMG instance using the Terraform example shown below.

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 2.1.1
- Terraform version: 1.5.7
- Provider version(s): 5 something, latest

## Reproduction Code [Required]

Make sure you setup your `AWS_` variables.

`terraform init && terraform plan`

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

locals {
  name = "my-own-grafana"
}

module "managed_grafana" {
  source  = "terraform-aws-modules/managed-service-grafana/aws"
  version = "~> 2"

  name                      = local.name
  account_access_type       = "CURRENT_ACCOUNT"
  authentication_providers  = ["AWS_SSO"]
  permission_type           = "SERVICE_MANAGED"
  data_sources              = ["PROMETHEUS"]
  notification_destinations = ["SNS"]
  grafana_version           = "9.4"

  # Workspace API keys
  workspace_api_keys = {
    admin = {
      key_name        = "admin"
      key_role        = "ADMIN"
      seconds_to_live = 3600
    }
  }
}
```

## Expected behavior

A working AMG.

## Actual behavior

Error due to missing SSO, even after enabling the AWS Identity Center in the UI for the same region the AMG is created in.

## Additional context

Not even using the underlying AWS provider resources. directly helped.

**Comment by bryantbiggs** [comment]
closing since this is an issue in the upstream API - here is an issue tracking that in the provider https://github.com/hashicorp/terraform-provider-aws/issues/24166
