### ISSUE TITLE
redundant hyphen sign ?

### ISSUE THREAD

**Issue by ofirmac** [terraform-aws-modules/terraform-aws-managed-service-grafana#31]
https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/14dc9a17539887d8c92456b6d4464f379d8c7bd1/main.tf#L70

if this hyphen sign is in purpose ?
can i remove it ?

`name_prefix = var.security_group_use_name_prefix ? "${local.security_group_name}-" : null`

**Comment by bryantbiggs** [comment]
> if this hyphen sign is in purpose ?

yes

>  can i remove it ?

no
