### ISSUE TITLE
Network Access Control requiring vpce_ids

### ISSUE THREAD

**Issue by PietroAvolio** [terraform-aws-modules/terraform-aws-managed-service-grafana#32]
## Description

Adding a `network_access_control ` attribute requires specifying `vpce_ids` while from the AWS Console it is possible to use a managed prefix list only.

- [v] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: Latest
- Terraform version: v1.6.4
- Provider version(s): 5.39.1

## Reproduction Code [Required]

`resource "aws_grafana_workspace" "main" {
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["AWS_SSO"]
  [...]
  grafana_version          = "9.4"

  network_access_control {
    prefix_list_ids = var.prefix_list_ids
  }`

## Expected behavior

Network access control configured with the specified Managed prefix list only.

Equivalent to
`aws grafana update-workspace --workspace-id g-xxx --network-access-control "{\"prefixListIds\": [\"pl-xxx\"], \"vpceIds\":[]}"`

## Actual behavior

`Error: Missing required argument
│
│   on ..\..\modules\grafana\main.tf line 10, in resource "aws_grafana_workspace" "main":
│   10:   network_access_control {
│
│ The argument "vpce_ids" is required, but no definition was found.`

**Comment by msarun003** [comment]
@PietroAvolio - As a workaround you may have a `vpce_ids` as a empty list, like below,

```
network_access_control = {
    vpce_ids        = []
    .......
    ....
  }
```
