### ISSUE TITLE
Add support for aws_grafana_workspace_service_account* resources

### ISSUE THREAD

**Issue by sidick** [terraform-aws-modules/terraform-aws-managed-service-grafana#35]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: introduced in AWS provider v5.59.0

## Is your request related to a problem? Please describe.

I would like to be able to create service accounts using Terraform

## Describe the solution you'd like.

A similar method to the existing API token configuration would likely make most sense

## Additional context

These resources are available from aws provider version 5.59.0
```
New Resource: aws_grafana_workspace_service_account (https://github.com/hashicorp/terraform-provider-aws/issues/38101)
New Resource: aws_grafana_workspace_service_account_token (https://github.com/hashicorp/terraform-provider-aws/issues/38101)
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.2.0 :tada:
