### ISSUE TITLE
Defaults for IAM permissions are inconsistent in variables and examples

### ISSUE THREAD

**Issue by philicious** [terraform-aws-modules/terraform-aws-managed-service-grafana#4]
## Description

With AWS Managed Grafana, you can choose between "Service Managed" or "Customer Managed" IAM permissions.
Either AWS creates IAM roles/policies for you or you supply your own.

**Code logic improvement**
Now, the code has conditional creation of IAM resources 
https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/bd896b807db7a4c7e8b69c0c4a8261dedc8bf1cc/main.tf#L36-L37

adding a sanity check `..&& var.permission_type == "CUSTOMER_MANAGED` could make sense imho

**Variable defaults issue**
The defaults are mismatching and dont make sense in that regard:
https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/bd896b807db7a4c7e8b69c0c4a8261dedc8bf1cc/variables.tf#L41-L44 and 
https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/bd896b807db7a4c7e8b69c0c4a8261dedc8bf1cc/variables.tf#L81-L84

defaults should either favor customer-managed or aws-managed creation. the business logic results in favoring customer-managed while the default of `permission_type` suggests differently

**Examples**
The "complete" example is misleading, as it again has `create_iam_role=true` together with `permission_type="SERVICE_MANAGED"`. While demonstrating all possible configurations, they still should make sense as some people copy blindly.

(Also the example in README has same flaw as it shows `permission_type="SERVICE_MANAGED"` together with `create_iam_role=true` from defaults.

**Comment by bryantbiggs** [comment]
Please try deploying v1.2.0 where you set 
```hcl
  permission_type     = "SERVICE_MANAGED"
  account_access_type = "CURRENT_ACCOUNT"
```

With at least one data source and let me know what policies are attached to the role.

Now change `account_access_type` to `"ORGANIZATION"`, re-deploy, and re-inspect the policies attached to the role

**Comment by philicious** [comment]
@bryantbiggs I will re-evaluate my finding/thoughts based on the previous version 1.2.0 as suggested and report 

I didnt take `account_access_type=ORGANIZATION` into consideration. Its not possible for me to try as 
>This mode is supported only for workspaces created in management accounts or delegated administrator accounts in an organization

and 

>In this mode, Amazon Managed Grafana creates all the IAM roles that are necessary to access AWS resources in other accounts in your AWS organization. In each account in the Organizational Units that you select, Amazon Managed Grafana creates a role called AmazonGrafanaOrgMemberRole-random-id. 

and I know the account is not the management account (while its still part of an Org tho)

**Comment by philicious** [comment]
so, @bryantbiggs I did some more testing and made some interesting observations.

one crucial quote I found upfront
> If you specify SERVICE_MANAGED on AWS Grafana console, Amazon Managed Grafana automatically creates the IAM roles and provisions the permissions that the workspace needs to use Amazon Web Services data sources and notification channels. **In CLI mode, the permissionType SERVICE_MANAGED will not create the IAM role for you**.

This sentence I found in the AWS CLI doc. Its not mentioned in the AWS doc, which only tells you first half !

SERVICE_MANAGED behaves just like CUSTOMER_MANAGED in CLI case

So if you try
```terraform
  permission_type                = "SERVICE_MANAGED"
  create_iam_role                = false
```
it will error 
> Error: error creating Grafana Workspace: ValidationException: When the accountAccessType is CURRENT_ACCOUNT a Workspace Role ARN should be provided.

while doing the same in UI will work !

So in case of this module, the only thing that makes sense is to use `create_iam_role = true` (or provide `iam_role_arn`). 
Having a variable `permission_type` is misleading when also consulting AWS docs. It should be hardcoded as its not truely variable. 
And also not expose it in examples. Maybe even add a note emphasizing on its special behavior in case of CLI/API 

PS: I only tested with 1.3.0 now

PSS: Given the fact that AWS wont create roles for you in CLI mode, I wonder if it would still do so if `account_access_type=ORGANIZATION`. I couldnt test. If not, this module would lack creation of them

**Comment by philicious** [comment]
ah yes that https://github.com/hashicorp/terraform-provider-aws/issues/24342 is exactly what I observed. However I fear that its not easily fixable as the CLI doc reads as its a (bad?!) design decision to behave like that via API. And CLI is mostly API.

so assuming it would be changed and CLI/API behaves like UI, **then** my initial post would be correct again: `create_iam_role=true` and `permission_type=SERVICE_MANAGED` would be mutually exclusive, or you end up with AWS-crated role/policy **and** by this module, where only one would effectively be used. 

sorry for the noise in case this was all known to you already :p

**Comment by bryantbiggs** [comment]
> sorry for the noise in case this was all known to you already :p

Not at all - its not always clear the paths that have been traversed that lead to the decisions made, etc. However, please do throw a 👍🏽 on that issue so maybe we can get some resolution - not sure if its a provider issue or an AWS API issue, but TBD
