### ISSUE TITLE
Add support for enabling grafana plugins

### ISSUE THREAD

**Issue by twellspring** [terraform-aws-modules/terraform-aws-managed-service-grafana#41]
## Is your request related to a new offering from AWS? No
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? Unsure.  

## Is your request related to a problem? Please describe.
The Managed Grafana 10.4 release changed removed xray from the list of plugins that are enabled by default.  The [aws_grafana_workspace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace) does not support enableing/disabling plugins, so any xray user migrating to this new version needs to manually enable this plugin.  

## Describe the solution you'd like.
Add the ability to enable/disable plugins to [aws_grafana_workspace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace).  AWS has an API to do this https://docs.aws.amazon.com/grafana/latest/userguide/Grafana-API-Plugin.html

## Describe alternatives you've considered.
- manually enabling x-ray
- Creating a null resource that runs a script to enable x-ray using the api https://docs.aws.amazon.com/grafana/latest/userguide/Grafana-API-Plugin.html

**Comment by bryantbiggs** [comment]
please check that the AWS provider supports this first - we cannot support without the provider supporting it
