### ISSUE TITLE
Grafana API key or a way to provision dashboards

### ISSUE THREAD

**Issue by maxkoko-co** [terraform-aws-modules/terraform-aws-managed-service-grafana#7]
Hi, I wonder is there a way to get an output of grafana api key or provision dashboards via json files while creating a grafana? Helm/Kubernetes created grafana has ways for it, but I cannot seem to find a way to do it via terraform with aws managed grafana. If there is no way to do it except for manual UI, then please do tell and sorry for bothering.

**Comment by bryantbiggs** [comment]
I am waiting on support for this to be added in https://github.com/hashicorp/terraform-provider-aws/issues/25100 which has a PR that is close https://github.com/hashicorp/terraform-provider-aws/pull/25286

After that is supported, I can finally start adding support for creating Grafana resources which I started awhile back till I ran into the current shortcomings https://github.com/bryantbiggs/terraform-aws-managed-service-grafana/tree/feat/grafana-sub-module/modules/grafana
